site_name: AudioSignal Documentation
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
nav:
  - Home: index.md
  - API Reference: api.md
  - Usage: usage.md
  - Installation: installation.md
docs_dir: docs
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
          paths: [src]
markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true
