site_name: AudioSignal Documentation
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png  # Place your logo at docs/assets/logo.png
  favicon: assets/favicon.ico  # Place your favicon at docs/assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - content.code.annotate
    - content.tabs.link
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
    - header.autohide
nav:
  - Home: index.md
  - API Reference: api.md
  - Usage: usage.md
  - Installation: installation.md
docs_dir: docs
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
          paths: [src]
markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.betterem
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SaarShafir/audio_signal
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/audio-signal/
  generator: false
